name: starmaven
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

  # Firebase - Stable versions
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6

  # Voice Assistant - Working versions
  speech_to_text: ^7.0.0
  flutter_tts: ^3.8.5
  permission_handler: ^11.3.1

  translator: ^0.1.7

  # OCR - Compatible version
  google_mlkit_text_recognition: ^0.9.0
  image_picker: ^1.0.7

  # State Management
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  flutter_riverpod: ^2.4.9

  # Additional utilities
  wakelock_plus: ^1.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/