// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_vxerjXK9CXPo6w5R1BqsC9sq2CcbKgk',
    appId: '1:885022658195:web:8e2ba255484b6fd66cc766',
    messagingSenderId: '885022658195',
    projectId: 'starmaven-ae8c9',
    authDomain: 'starmaven-ae8c9.firebaseapp.com',
    storageBucket: 'starmaven-ae8c9.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8q24_zj-ABFN44wWrQQF8EqR3ucTkZYI',
    appId: '1:885022658195:android:576d105a91cc884b6cc766',
    messagingSenderId: '885022658195',
    projectId: 'starmaven-ae8c9',
    storageBucket: 'starmaven-ae8c9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmoHPA7UrJYo1mj1GrvzHSVaRu9iyXatk',
    appId: '1:885022658195:ios:5aa8cb180689f64c6cc766',
    messagingSenderId: '885022658195',
    projectId: 'starmaven-ae8c9',
    storageBucket: 'starmaven-ae8c9.firebasestorage.app',
    iosBundleId: 'com.example.starmaven',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmoHPA7UrJYo1mj1GrvzHSVaRu9iyXatk',
    appId: '1:885022658195:ios:5aa8cb180689f64c6cc766',
    messagingSenderId: '885022658195',
    projectId: 'starmaven-ae8c9',
    storageBucket: 'starmaven-ae8c9.firebasestorage.app',
    iosBundleId: 'com.example.starmaven',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_vxerjXK9CXPo6w5R1BqsC9sq2CcbKgk',
    appId: '1:885022658195:web:703c64e97a9514836cc766',
    messagingSenderId: '885022658195',
    projectId: 'starmaven-ae8c9',
    authDomain: 'starmaven-ae8c9.firebaseapp.com',
    storageBucket: 'starmaven-ae8c9.firebasestorage.app',
  );
}
